language: node_js
sudo: false
node_js:
  - 5.4.1

env:
  global:
    - CXX=g++-4.8
    - SAUCE_USERNAME=SteveVanOpstal
    - secure: fGMOrTaL4fJrZkQfwoC3/PZykjmeverJyPXhn7pGgq5sAHxB/xmZlG6tj4hi6Dxubjpr35aQ7D9oe+ml3TcRhE0TnQnYPhCOy76SX1UsuP1eiUxNfIMqmWy29rBzvLLqBqsSna9FcKE1cgaj/CyPP31vMZdeOOmFkAjvsZ/ydadugrwLB2zLPAPegWmmZyDmi/UamjbgvflvGT8tQ51JK6bU4V73WSKMcO+O8O5pLsQVf2qUIKmyQXzhawhTutNL+33GCa4cpG/HaoczNRdyeUJ/x/o0mLN3ltwjRmUYbl6EjbfkcGjAQhr/GG80mBbGsJPkUV8XCVpVXaRA1gV4SdPGAAIz13QY0p0I8tjEISud2KMp4bi+ixmx1/nl5iwbJjJg6LsSVPa/v+Me31o/fDaYoxjeYiBHJB8JDH7t7OomIsPoXl85HB9PFzrUQBb/WM79h+fgQuN7Pg2cktSbsRPZQ9i6BI6OIXFyywyY7D2BwSmfL7Tg1SbgpQbzkLTHOzfLaeW9zM9yO6D9mFp65Dr4nlA9WMtASH0g+K1jTQ8NubFULwghWtNmS+NUY8S6NPUtOzcA4IHGKY3XO8FT687X399gcx9lk82i/IuWwpmsF097Wdqzz6u/sLU7Tl1QQj6yjMNVydCPtrSnmefAbfOyFp0PCny90TKuxRuSe6k=
  matrix:
    - CI_MODE=client
    - CI_MODE=client_test_required
    - CI_MODE=client_test_optional
    - CI_MODE=server
    - CI_MODE=server_test

matrix:
  allow_failures:
    - env: CI_MODE=client_test_optional

cache:
  directories:
    - node_modules

install:
  - npm install

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3

script:
  - npm run ci
