language: node_js
sudo: false
node_js:
  - '5.4.1'

env:
  - CXX=g++-4.8

cache:
  directories:
    - node_modules

before_install:
  - rm -rf node_modules/

install:
  - npm install

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3 # give xvfb some time to start

script:
  - npm run test
  - npm run build

after_script:
  - npm run coveralls