language: node_js
sudo: false
node_js:
  - '5.4.1'

env:
  - CXX=g++-4.8

cache:
  directories:
    - node_modules

install:
  - npm install

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
